platform :ios, '10.0'

target 'Vision Face Detection' do

    use_frameworks!
    
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'SwiftSocket'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Facebook'

end
